/*
 * Copyright (c) 2021 André Andrade - alandrade21@gmail.com
 * 
 * This file is part of the "electron-arch" library.
 *
 * "electron-arch" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * "electron-arch" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with "electron-arch".  If not, see <https://www.gnu.org/licenses/>.
 */

import { ErrorWrapper } from '../errors/ErrorWrapper';

/**
 * Class to represent an error generated by a try to run the app in a operational 
 * system different from win32, linux or darwin (macOs), if the app runs at all.
 * 
 * @since 0.0.1
 */
export class InvalidPlatformError extends ErrorWrapper {
  // Override
  protected _classifier = 'PLATFORM_ERROR';

  // Override
  protected _className = 'InvalidPlatformError';

  constructor(){
    super(`The operational system ${process.platform} is not supported.`);
  }
}